### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by emadbagheri96** [tilmanmoser/bbb-video-download#1]
hi
first thanks for sharing the script
i have previously installed another node script which used pupitter for creating a single video file from presentations. when i tried to install your script, it showed some errors about node and npm version requirement (they were outdated). then i updated them and got able to installed your script successfully.
now after a recording is published an empty video.mp4 file is created and i'm getting this error from log which is generated from `/modules/processor.js#L60`:
```
Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
Error initializing output stream 0:0 --
Conversion failed!
```
here was the result of searching for the error: https://stackoverflow.com/a/39679975
```
the mp4 container requires the ability to seek within the file. A pipe is a stream, and impossible to seek inside of. Try using a streaming container like ts, or flv.
```
my recording contains desktop sharing if it is related to the concept.
what is the problem?
is it related to the MPEG4 license you mentioned?

**Comment by tilmanmoser** [comment]
Did you use install.sh? You should not(!) update node, since bbb relies on node v8. The install script installs node12 binaries inside the installation folder. Also: the post script will be executed by the user bigbluebutton, which must be able to write files into the installation folder. That‘s why the install script (executed as root) changes ownership. Pls try to execute the script manually aus described in the readme and post the console log.

**Comment by tilmanmoser** [comment]
Also: the script does not rely on deskshare video. It should work fine with audio only and/or webcams and/or presentations and/or deskshare.

**Comment by emadbagheri96** [comment]
> 
> 
> Did you use install.sh? You should not(!) update node, since bbb relies on node v8. The install script installs node12 binaries inside the installation folder. Also: the post script will be executed by the user bigbluebutton, which must be able to write files into the installation folder. That‘s why the install script (executed as root) changes ownership. Pls try to execute the script manually aus described in the readme and post the console log.

yes, i used install.sh and got the nodejs version error
i will try again and tell you the result
also i suggest to point out running the script as **root** in the doc

**Comment by tilmanmoser** [comment]
It's in the instructions - `**sudo** ./install.sh`. Please provide console log when you run the script manually, like pointed out.

```bash
cd /path/to/bbb-video-download
./node12/bin/node index.js -i /var/bigbluebutton/published/presentation/<presentationid> -o yourvideo.mp4
```

**Comment by emadbagheri96** [comment]
i just reinstalled os and everything fresh and it works fine.
I have a few questions:
I have the minimum server ( 4 core cpu and 8 gb ram). for making the video file first it uses puppeteer with chromium which uses a single cpu core's 100% to record, then ffmpeg uses multi cores (about 40% each) to do its job. so in production have you tested it when there are multi users using the server's web conference service and the script is running the record as well?
is it possible to delay the post script recording to some time when there is no active meeting?

**Comment by tilmanmoser** [comment]
> Seems like it had problem with my previous stuff. I just reinstalled os and everything fresh and it works fine.
Great!

> I have the minimum server ( 4 core cpu and 8 gb ram). for making the video file first it uses puppeteer with chromium which uses a single cpu core's 100% to record, then ffmpeg uses multi cores (about 40% each) to do its job. so in production have you tested it when there are multi users using the server's web conference service and the script is running the record as well?
My solution is **not** screenrecording the bbb playack. It parses the produced media artefacts (videos, images, events), creates assets (whiteboard drawings, etc) and renders a single video file from the various inputs with ffmpeg. Pupeteer/Chromium is used in assert-creation-phase to render pngs from svg-shapes. For most shapes it would be faster to use different libraries (like node-sharp or imagemagick), but for multilinetext I need the headless chromium browser, since I need to render a html paragraph. That all said the runtime of the processing depends on your cpu speed, i.e. it can be shorter than the playback duration.

> is it possible to delay the post script recording to some time when there is no active meeting?
You could write a post_publish-hook that only saves the published presentation ids to a file and use that file to produce video files at a suitable time by invoking my script with the input and output paths. But bbb is anyway processing your recordings after every finished meeting. So you would only postpone the rendering of the single video file but the rendering of the native bbb video files.
