### ISSUE TITLE
Video resolution

### ISSUE THREAD

**Issue by jmmena** [tilmanmoser/bbb-video-download#46]
Tilman, great work! 
This isn´t a issue. I´ve tested the scritp and it works ok. 
Only one question: the output video resolution is 800x600. I wonder if it would be possible to configure the script for another type of resolution, for example 1280x720. This is the deskshare.webm original file resolution (in the example i´ve tested).
thanks in advance

**Comment by tilmanmoser** [comment]
Hi. Video resolution is derived from the viewport settings in shapes.svg as set by big blue button itself; i.e. different presentations may have different video resolutions. The presentation video is created by taking screenshots from this file in a headless chromium browser. Setting another viewport could result in odd aspect ratios. But you could resize the whole video with ffmpeg easily afterwards.

**Comment by jmmena** [comment]
Hi! Ok, that´s clear. 
Thanks for your answer (and for the script)

**Comment by tilmanmoser** [comment]
Just to make that point clear: I marked this as an enhancement, since I understand that it would be good to have some control over the resulting video resolution. It's just not trivial and I add it to the mabe-later-list :-)

**Comment by osintaras** [comment]
Thank you for your good work! 
Please tell me in which file you can change the resolution of the final video, while you have not done it yet?

**Comment by tilmanmoser** [comment]
Hi @osintaras - I'm currently not intending to build this into the script, since there are two issues with it:
1) If the desired video resolution is higher than the actual source material, it would result in a grainy video, which is not desired.
2) Resizing the video during composition results in ffmpeg reencoding the whole video, which results in significant longer run time and resource usage.

I suggest you resize the video after creation with a command like `ffmpeg -i video.mp4 -vf scale=320:-2 video2.mp4`.

**Comment by parreitu** [comment]
Hi @tilmanmoser  

I agree with @osintaras , it'd be great it we could configure the resolution of the virtual browser in order to change the resolution of the result video.

Thanks for your great job !
