### ISSUE TITLE
TypeError: Cannot read property 'threads' of undefined

### ISSUE THREAD

**Issue by lonesomewalker** [tilmanmoser/bbb-video-download#82]
```
TypeError: Cannot read property 'threads' of undefined
    at stackWebcamsToPresentation (/home/bigbluebutton/modules/processor.js:73:91)
    at combinePresentationWithWebcams (/home/bigbluebutton/modules/processor.js:54:15)
    at module.exports.createVideo (/home/bigbluebutton/modules/processor.js:21:29)
    at async run (/home/bigbluebutton/index.js:10:9)****
```

code line:
```
childProcess.execSync(`ffmpeg -hide_banner -loglevel error -threads ${config.args.threads} -i ${presentation.video} -i ${webcams.video} -filter_complex "[0:v]pad=width=${width}:height=${height}:color=white[p];[p][1:v]overlay=x=${presentation.width}:y=0[out]" -map [out] -map 1:1 -c:a aac -shortest -y ${output}`)
```

seems there is no default definition of threads... which should be at least one.

**Comment by lonesomewalker** [comment]
Even after manually fixing this, i get a lot of other errors... seriously, who botched that SO HARD (@Superjamp ) without even testing it?

Consider a revert.

**Comment by tilmanmoser** [comment]
@Superjamp, @lonesomewalker - I reverted the changes to the last pull request.

Since I don't have the time to actively maintain this script at the moment, I'm grateful for every help / pull request. @Superjamp, if you find the time to fix the mentioned issues, I'm more than happy to accept the next pull request from you.

**Comment by lonesomewalker** [comment]
It is really hard nowadays to see stuff checked BEFORE a pull request, totally agree to that.
I like the idea with more switches (like threads), but then they should be documented AND working. Which is obviously NOT the case.

@Superjamp did you test this yourself to git checkout on a plain new 2.4 instance (because that is the latest official stable one) without any modification from your university?
Did it work as expected?

If so, please show me that.

If not, why did you do this pull request and break the code?


thx

**Comment by Superjamp** [comment]
Yes, we were not using `stackWebcamsToPresentation()` and it just seems that I missed adding the `config` param at the call of the function. https://github.com/tubraunschweig/bbb-video-download/commit/c49ee8bfc23a70efb1135dc1e2822f297ae6b105
To create a revert commit is not the best option I guess, but you probably will find a way to solve it.

I'm currently using [danielpetri1/bbb-recording-exporter](https://github.com/danielpetri1/bbb-recording-exporter) with some modifications regarding deskshare and local dependencies.
Instead of puppeteer to create Screenshots, It is directly concatenating svg's with ffmpeg.
From Hours of running with puppeteer (with higher quality Screenshots `deviceScaleFactor=3`), it's only taking minutes to create the Video.
At the beginning of 2020, I followed the same ffmpeg approach on my own, but could not figure out how to render text on slides.
Recently I had time to invest in this Problem and saw this puppeteer style of approach again and started to adapt it.
After I saw It was really slow to create higher/same quality Videos and found that someone with more time figured it out, I switched to the above-mentioned project.

**Comment by lonesomewalker** [comment]
If the quality from danielpetri/bbb-recording-exporter is the same as his last pull-request: no, thank you.

You know, your PRs are related to tubraunschweig, since you actively promote this in your github profile.
Means: also your quality is part of this.

For later PRs, please test this BEFORE submitting.
Saves others debugging.

**Comment by defnull** [comment]
I find the tone of Lonesomewalkers last comment quire irritating. Enough so that I'd like to voice my concerns and not just ignore it as usual.

This is open source. The code in this repository is meant to solve Tilmans problem, not yours. It is not a product, he does not claim to have the best solution, he does not try to sell it and you did not pay for it. The code is here because the author was kind enough to share it, for free, so it may help others with similar problems. Sebastian contributed and tried to improve this project, also for free and with no obligation to do so. Yes, there was a bug. Software has bugs. Go figure.

This is open source. If it does not work _for you_, fix it or leave it. If you can't fix it yourself, pay someone who can. The last paragraph of the License text is written in all caps for a reason. People tend to miss that part. You are in no situation to demand anything from anyone. Tilman has no obligations to meet your quality standards or to fix a feature you need, and demanding an explanation from Sebastian why he dared to submit an imperfect PR is just toxic. This demanding and judging behavior is what drives many talented developers away from doing open source work in their free time and keep their code private instead. This is what turns a fun little hobby project into something that feels like work you do not want to do anymore. Yes, I'm projecting here. Obviously. Sorry for the rant.

**Comment by Superjamp** [comment]
❤️  @defnull

Yes, I know I missed something during development. And I will learn from it and do better in the future.
I just wanted to contribute our/my local Changes to the project. That could have made this project even better. 

At the moment, I don't feel ok testing the `stackWebcamsToPresentation()` function.
I have done it anyway and had no Problems running the default settings based on my latest PR and the local dependencies in the compose file.

@lonesomewalker You could have also shared with us the additional problems you are facing.

**Comment by lonesomewalker** [comment]
@defnull: 

> This is open source. The code in this repository is meant to solve Tilmans problem, not yours. It is not a product, he does not claim to have the best solution, he does not try to sell it and you did not pay for it. The code is here because the author was kind enough to share it, for free, so it may help others with similar problems. Sebastian contributed and tried to improve this project, also for free and with no obligation to do so. Yes, there was a bug. Software has bugs. Go figure.

F*cking NO. Code has NO bugs. Humans make them. That is the funny excuse a lot of developers are thinking about bugs.
Also you are working for an university, right? Even better, a company offering support.
We don't hire university people anymore because of their ignorance and denying responsibility (like you do now).

> This is open source. If it does not work _for you_, fix it or leave it.

How about NOT breaking it in the first run?

> If you can't fix it yourself, pay someone who can.

Funny thing for you: instead of just providing support for a small university we provide support for several counties.
Now, compared to that, and given the fact that you support somebody who broke code which worked before... this is the kind of software and IT quality we find A LOT when we do incident response.

So, instead of bragging about free software you should also care about taking responsibility for mistakes.
Your rant isn't worth the energy it cost to post.

Oh wait, there is something else: did you or your company donate to @tilmanmoser ?
No? Well, guess what...

@Superjamp:
i don't know who you are, but related to public information you do this 5 years and 8 months.
And you are contributing without testing it before?
Basic principles of doing pull requests: missed
Basic principles of covering up mistakes: missed

No, i can not accept such ignorance.
It is good that you say now, you will try harder in the future, but you also mentioned another project which seems to suit better for your needs.
So, why did you commit here?

And no, why should i share my additional problems which have been caused by your pull request?
Because when you revert it, it works perfectly fine.
So, where are the additional problems then?

Guys, it is always nice to see somebody f*cking things up and there is an assistant who tries to defend the botched submit.
Grow some balls, take responsibility!
